

const FILE_IS_TOO_BIG = 'FILE_IS_TOO_BIG';
const NOT_ENOUGH_STORAGE = 'NOT_ENOUGH_STORAGE';
const EMPTY_TRASH = 'EMPTY_TRASH';
const SOURCE_CARD_NOT_COPYABLE = 'SOURCE_CARD_NOT_COPYABLE';
const SOURCE_CARD_NOT_MOVABLE = 'SOURCE_CARD_NOT_MOVABLE';

export default {
  FILE_IS_TOO_BIG,
  NOT_ENOUGH_STORAGE,
  EMPTY_TRASH,
  SOURCE_CARD_NOT_COPYABLE,
  SOURCE_CARD_NOT_MOVABLE,
};
